### ISSUE TITLE
French rarity 

### ISSUE THREAD

**Issue by voldenveiem** [physanus/SkyBlock-Stats-Docker#1]
For the french players ( like me ) the name of common, epic and legendary rarity have been traducted in french, what create little bugs with the weapon, armor and talisman with this rarity for french player.

traductions : 
common became commun
epic became epique 
legendary became légendaire
![image](https://user-images.githubusercontent.com/68890601/88627499-b18d4800-d0ac-11ea-9272-7136cd076043.png)

**Comment by physanus** [comment]
Hey! 
This repo aims to implement a docker container for Leas Skyblock stats (which actually does not work anymore since the dependencies changed, work needs to be done there). However, it is in no way related to her project or bugs.
You may want to report your bug at her issue tracker, right here: https://github.com/LeaPhant/skyblock-stats/issues

**Comment by voldenveiem** [comment]
ok, thanks
